version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile.node
    volumes:
      -  /Users/hgshivakumar/Desktop/Audio_Books:/audiobooks_dir
    ports:
    - '3011:3010'

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    links:
      - node:node
    ports:
      - '80:80'
    volumes:
      - /Users/hgshivakumar/node_apps/audiobile_webapp/build:/usr/webapp